import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { transform } from '@svgr/core';
import jsx from '@svgr/plugin-jsx';

const ICONS_SVG_DIR = path.resolve(import.meta.dirname, '../packages/icons/svg');
const REACT_ICONS_DIR = path.resolve(import.meta.dirname, '../packages/react/src/icons');
const REACT_INDEX_PATH = path.resolve(import.meta.dirname, '../packages/react/src/index.ts');

function toPascalCase(kebab: string) {
  const pascal = kebab
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  // A leading digit (e.g. "24-support" -> "24Support") isn't a valid JS
  // identifier, so it can't be used as an export name as-is.
  return /^[0-9]/.test(pascal) ? `Icon${pascal}` : pascal;
}

// SVGR's default output (with ref + expandProps) shapes the component as:
//   const SvgFoo = (props: SVGProps<SVGSVGElement>, ref: React.Ref<SVGSVGElement>) => (<svg ...>...)
// We patch that signature to add a `size` prop (default 24) and wire it to
// width/height, since we strip the source SVGs' own width/height in the
// optimize step (`dimensions: false` below) so only viewBox remains.
async function generateComponent(svg: string, componentName: string) {
  const code = await transform(
    svg,
    {
      plugins: [jsx],
      typescript: true,
      ref: true,
      dimensions: false,
      expandProps: 'end',
      replaceAttrValues: {
        '#000': 'currentColor',
        '#000000': 'currentColor',
        black: 'currentColor',
        // Iconsax/Vuesax's default icon ink color (case as exported by Figma).
        '#292D32': 'currentColor',
        '#292d32': 'currentColor',
      },
    },
    { componentName },
  );

  return code
    .replace(
      /\(\s*props:\s*SVGProps<SVGSVGElement>\s*,\s*ref:\s*(React\.)?Ref<SVGSVGElement>\s*\)/,
      '({ size = 24, ...props }: SVGProps<SVGSVGElement> & { size?: number | string }, ref: $1Ref<SVGSVGElement>)',
    )
    .replace('<svg', '<svg width={size} height={size}');
}

async function main() {
  const files = (await readdir(ICONS_SVG_DIR)).filter((f) => f.endsWith('.svg'));

  await rm(REACT_ICONS_DIR, { recursive: true, force: true });
  await mkdir(REACT_ICONS_DIR, { recursive: true });

  if (files.length === 0) {
    await writeFile(REACT_INDEX_PATH, '// Generated by `pnpm codegen:react` — do not edit by hand.\nexport {};\n');
    console.log('No SVGs found in packages/icons/svg. Run "pnpm fetch:figma" first.');
    return;
  }

  const exportsList: string[] = [];

  for (const file of files) {
    const kebabName = file.replace(/\.svg$/, '');
    const componentName = toPascalCase(kebabName);
    const svg = await readFile(path.join(ICONS_SVG_DIR, file), 'utf-8');
    const code = await generateComponent(svg, componentName);
    await writeFile(path.join(REACT_ICONS_DIR, `${kebabName}.tsx`), code, 'utf-8');
    exportsList.push(`export { default as ${componentName} } from './icons/${kebabName}.js';`);
    console.log(`  ✓ ${componentName}`);
  }

  exportsList.sort();
  const header = '// Generated by `pnpm codegen:react` — do not edit by hand.\n';
  await writeFile(REACT_INDEX_PATH, header + exportsList.join('\n') + '\n', 'utf-8');
  console.log(`\nGenerated ${files.length} React components.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
